### ISSUE TITLE
A Java Script error occured in the main process

### ISSUE THREAD

**Issue by Gamerbiomek2** [portapps/discord-ptb-portable#25]
keeps showing up before opening the program
![Discord PTB javaScript error](https://user-images.githubusercontent.com/22333494/93727264-66615400-fb88-11ea-9a7c-430cf90b5d06.png)

**Comment by crazy-max** [comment]
@Gamerbiomek2 Please create a proper [bug report](https://github.com/portapps/discord-ptb-portable/issues/new?template=bug_report.md).
