### ISSUE TITLE
Not compatible with BandagedBD

### ISSUE THREAD

**Issue by spartaque12** [portapps/discord-ptb-portable#29]
#### Steps to reproduce this issue

1.install discordptb portable
2.install latest BandagedBD (better discord)

#### Expected behaviour

it should work i suppose

#### Actual behaviour

list of errors
### Configuration

**App release:
 win32-0.0.55-12

**Operating system:
Win10x64

**Winver screenshot** :
https://imgur.com/kZLoQPB

### Screenshots
https://imgur.com/stZexeD

### Logs

[discord-ptb-portable.log](https://github.com/portapps/discord-ptb-portable/files/5458965/discord-ptb-portable.log)

**Comment by hermaherp** [comment]
Can confirm, the program crashes if BBD is installed, either by the installer or the manual way

**Comment by crazy-max** [comment]
BandagedBD is not compatible with Discord PTB portable as it overwrites required files inside `app` folder.
